[package]
name = "rs-git-fsmonitor"
version = "0.1.2"
authors = ["Jason Gavris <jgavris@gmail.com>", "Matt Kline <matt@bitbashing.io>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
failure = "0.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
